version: "3.2"
services:
  bot:
    build: .
    init: true
    ports:
      - "3000:3000"
    volumes:
      - ./sqlite3:/app/sqlite3
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    working_dir: /app
    command: node build/index.js
